// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppConf(arg1) {
  return window['go']['main']['App']['AppConf'](arg1);
}

export function ConnsOpened() {
  return window['go']['main']['App']['ConnsOpened']();
}

export function DBConf(arg1) {
  return window['go']['main']['App']['DBConf'](arg1);
}

export function DescribeConsumerGroups(arg1, arg2) {
  return window['go']['main']['App']['DescribeConsumerGroups'](arg1, arg2);
}

export function DescribeTopics(arg1, arg2) {
  return window['go']['main']['App']['DescribeTopics'](arg1, arg2);
}

export function GetConsumerGroupMessageLag(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetConsumerGroupMessageLag'](arg1, arg2, arg3);
}

export function GetMessageByOffset(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMessageByOffset'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListConsumerGroups(arg1) {
  return window['go']['main']['App']['ListConsumerGroups'](arg1);
}

export function ListTopics(arg1) {
  return window['go']['main']['App']['ListTopics'](arg1);
}

export function OpenConn(arg1) {
  return window['go']['main']['App']['OpenConn'](arg1);
}

export function SetAPPConf(arg1) {
  return window['go']['main']['App']['SetAPPConf'](arg1);
}

export function SetDBConf(arg1) {
  return window['go']['main']['App']['SetDBConf'](arg1);
}

export function TailMessage(arg1, arg2) {
  return window['go']['main']['App']['TailMessage'](arg1, arg2);
}
